//! The frontier, the verdict, and the README's results.
//!
//! Everything here is a pure function of `results/`: the README's results
//! section is regenerated from those files and `--check` fails when the two
//! disagree, so no number in the README can drift from its evidence.

mod data;
mod render;
mod verdict;

use anyhow::{Context, Result, bail};

use crate::util::root;

const BEGIN: &str = "<!-- results:begin (generated by `cargo xtask report`; do not edit) -->";
const END: &str = "<!-- results:end -->";

/// `xtask report [--check]`.
pub fn report(args: &[String]) -> Result<()> {
    let data = data::Data::load()?;
    let verdicts = verdict::judge(&data);
    let body = render::render(&data, &verdicts);
    crate::util::write_json(&root().join("results/verdict.json"), &verdict::to_json(&verdicts))?;
    let path = root().join("README.md");
    let readme = std::fs::read_to_string(&path).context("reading README.md")?;
    let (Some(start), Some(end)) = (readme.find(BEGIN), readme.find(END)) else {
        bail!("README.md has no results markers");
    };
    let updated = format!("{}{BEGIN}\n\n{body}\n{}", &readme[..start], &readme[end..]);
    if args.iter().any(|a| a == "--check") {
        if updated != readme {
            bail!("README.md results are stale: run `cargo xtask report`");
        }
        eprintln!("report: README.md is current");
        return Ok(());
    }
    std::fs::write(&path, updated)?;
    eprintln!("report: wrote README.md and results/verdict.json");
    Ok(())
}
